# Generated by Django 4.2.4 on 2023-09-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment_likes_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes_num',
        ),
        migrations.RemoveField(
            model_name='likes_table',
            name='comment',
        ),
    ]
