# Generated by Django 4.2.4 on 2023-09-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_comment_options_comment_comments_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes_table',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
    ]
