# Generated by Django 4.2.4 on 2023-09-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments_num',
            new_name='child_comments_num',
        ),
    ]
