# Generated by Django 4.2.4 on 2023-09-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_rename_comments_num_comment_child_comments_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
