# Generated by Django 4.2.4 on 2023-09-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='posts/videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, to='posts.image'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='posts/images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.ManyToManyField(blank=True, to='posts.video'),
        ),
    ]
