# Generated by Django 4.2.4 on 2023-09-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_video_remove_article_image_article_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type',
            new_name='content_type',
        ),
    ]
