# Generated by Django 4.2.4 on 2023-08-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='caption',
            field=models.TextField(blank=True, default='...'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
