# Generated by Django 4.2.4 on 2023-09-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_likes_table_comment_alter_likes_table_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
    ]
