# Generated by Django 4.2.4 on 2023-10-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_remove_article_video_article_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='image',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.image'),
        ),
    ]
